version: '3.9'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/backend_api
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: root
      POSTGRES_PASSWORD: '12345678'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
