version: '3.9'

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - .:/frontend_api
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: frontend
      POSTGRES_USER: root
      POSTGRES_PASSWORD: '12345678'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: